---
abstract: 'A simple parallel processing fork manager with AnyEvent'
author:
  - 'Kenta Sato <karupa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::SharedFork: 0
  Time::HiRes: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.53, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-ForkManager
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  AnyEvent::ForkManager:
    file: lib/AnyEvent/ForkManager.pm
    version: 0.04
requires:
  AnyEvent: 0
  Class::Accessor::Lite: 0.04
  POSIX: 0
  Scalar::Util: 0
  Time::HiRes: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/karupanerura/p5-AnyEvent-ForkManager/issues
  homepage: https://github.com/karupanerura/p5-AnyEvent-ForkManager
  repository: git://github.com/karupanerura/p5-AnyEvent-ForkManager.git
version: 0.04
x_contributors:
  - 'かるぱねるら <karupanerura@karupas-mbp.local>'
