---
abstract: 'A simple parallel processing fork manager with AnyEvent'
author:
  - 'Kenta Sato <karupa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.06
  Test::SharedFork: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: AnyEvent::ForkManager
name: AnyEvent-ForkManager
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  Class::Accessor::Lite: 0.04
  POSIX: 0
  Scalar::Util: 0
  Time::HiRes: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/karupanerura/p5-AnyEvent-ForkManager.git
version: 0.02
